const playlists = [
    {
      id: 1,
      name: 'Избранное',
      posterUrl: '../files/img/posters/favorite.jpg',
      defaultLikes: 1,
      defaultElect: true,
      tracks: [
        {
          id: 1,
          title: 'Fire Man -',
          artist: 'Miyagi & Эндшпиль',
          censore: true,
          path: '../files/audio/playlist_1/1.mp3',
          duration: '3:37',
        },
        {
          id: 2,
          title: 'Без даты -',
          artist: 'Remix - YHHB',
          censore: true,
          path: '../files/audio/playlist_1/2.mp3',
          duration: '3:29',
        },
        {
          id: 3,
          title: 'Кровь на танцполе -',
          artist: 'Mujuice',
          censore: false,
          path: '../files/audio/playlist_1/3.mp3',
          duration: '4:40',
        },
        {
          id: 4,
          title: 'Юность -',
          artist: 'Mujuice',
          censore: false,
          path: '../files/audio/playlist_1/4.mp3',
          duration: '6:33',
        },
        {
          id: 5,
          title: 'HDMI -',
          artist: 'Bones',
          censore: true,
          path: '../files/audio/playlist_1/5.mp3',
          duration: '2:19',
        },
        {
          id: 6,
          title: 'In The End -',
          artist: 'Linkin Park',
          censore: false,
          path: '../files/audio/playlist_1/6.mp3',
          duration: '3:39',
        },
        {
          id: 7,
          title: 'Sonne -',
          artist: 'Rammstein',
          censore: false,
          path: '../files/audio/playlist_1/7.mp3',
          duration: '4:32',
        },
        {
          id: 8,
          title: 'After Dark -',
          artist: 'Mr.Kitty',
          censore: false,
          path: '../files/audio/playlist_1/8.mp3',
          duration: '4:17',
        },
        {
          id: 9,
          title: 'Little Dark Age -',
          artist: 'MGMT',
          censore: false,
          path: '../files/audio/playlist_1/9.mp3',
          duration: '4:59',
        },
        {
          id: 10,
          title: 'Lost On You -',
          artist: 'LP',
          censore: false,
          path: '../files/audio/playlist_1/10.mp3',
          duration: '4:26',
        },
        {
          id: 11,
          title: 'We Will Rock You -',
          artist: 'Queen',
          censore: false,
          path: '../files/audio/playlist_1/11.mp3',
          duration: '2:01',
        },
        {
          id: 12,
          title: 'Тело -',
          artist: 'ЛСП',
          censore: true,
          path: '../files/audio/playlist_1/12.mp3',
          duration: '3:44',
        },
        {
          id: 13,
          title: 'River -',
          artist: 'Anonymouz',
          censore: false,
          path: '../files/audio/playlist_1/13.mp3',
          duration: '3:21',
        },
      ],
    },
    {
      id: 2,
      name: 'Tiny Bunny vibe / Зайчик',
      posterUrl: '../files/img/posters/bunny.jpg',
      defaultLikes: 25614,
      defaultElect: false,
      tracks: [
        {
          id: 1,
          title: 'Зима -',
          artist: 'ooes',
          censore: false,
          path: '../files/audio/playlist_2/1.mp3',
          duration: '2:28',
        },
        {
          id: 2,
          title: 'Мальчик на девятке -',
          artist: 'DEAD BLONDE',
          censore: false,
          path: '../files/audio/playlist_2/2.mp3',
          duration: '3:35',
        },
        {
          id: 3,
          title: 'Белая ночь -',
          artist: 'Черниковская хата',
          censore: false,
          path: '../files/audio/playlist_2/3.mp3',
          duration: '3:58',
        },
        {
          id: 4,
          title: 'Тоска -',
          artist: 'MOLCHAT DOMA',
          censore: false,
          path: '../files/audio/playlist_2/4.mp3',
          duration: '3:09',
        },
        {
          id: 5,
          title: 'Последнее лето -',
          artist: 'ooes',
          censore: false,
          path: '../files/audio/playlist_2/5.mp3',
          duration: '2:17',
        },
        {
          id: 6,
          title: 'Судно -',
          artist: 'MOLCHAT DOMA',
          censore: true,
          path: '../files/audio/playlist_2/6.mp3',
          duration: '2:21',
        },
        {
          id: 7,
          title: 'Смерти больше нет -',
          artist: 'IC3PEAK',
          censore: false,
          path: '../files/audio/playlist_2/7.mp3',
          duration: '3:22',
        },
        {
          id: 8,
          title: 'Сказка -',
          artist: 'IC3PEAK',
          censore: false,
          path: '../files/audio/playlist_2/8.mp3',
          duration: '2:45',
        },
        {
          id: 9,
          title: 'Пластинки -',
          artist: 'дурной вкус',
          censore: false,
          path: '../files/audio/playlist_2/9.mp3',
          duration: '3:04',
        },
        {
          id: 10,
          title: 'Группа крови -',
          artist: 'Кино',
          censore: false,
          path: '../files/audio/playlist_2/10.mp3',
          duration: '4:46',
        },
        {
          id: 11,
          title: 'Первый снег -',
          artist: 'Сова',
          censore: false,
          path: '../files/audio/playlist_2/11.mp3',
          duration: '2:58',
        },
        {
          id: 12,
          title: 'Снова -',
          artist: 'Беспокойник',
          censore: false,
          path: '../files/audio/playlist_2/13.mp3',
          duration: '2:49',
        },
        {
          id: 13,
          title: 'Бесприданница -',
          artist: 'DEAD BLONDE',
          censore: false,
          path: '../files/audio/playlist_2/12.mp3',
          duration: '3:00',
        },
        {
          id: 14,
          title: 'DEATH IS NO MORE -',
          artist: 'BLESSED MANE',
          censore: false,
          path: '../files/audio/playlist_2/14.mp3',
          duration: '2:23',
        },
        {
          id: 15,
          title: 'Ведьмы -',
          artist: 'BALKON',
          censore: false,
          path: '../files/audio/playlist_2/15.mp3',
          duration: '3:21',
        },
      ],
    },
    {
      id: 3,
      name: 'Electro Music',
      posterUrl: '../files/img/posters/electro.jpg',
      defaultLikes: 54,
      defaultElect: true,
      tracks: [
        {
          id: 1,
          title: 'Delusive Bunker -',
          artist: 'Ludowic',
          censore: false,
          path: '../files/audio/playlist_3/1.mp3',
          duration: '5:12',
        },
        {
          id: 2,
          title: 'Murder In My Mind -',
          artist: 'Kordhell',
          censore: false,
          path: '../files/audio/playlist_3/2.mp3',
          duration: '2:25',
        },
        {
          id: 3,
          title: 'Dream Space -',
          artist: 'DVRST',
          censore: false,
          path: '../files/audio/playlist_3/3.mp3',
          duration: '2:51',
        },
        {
          id: 4,
          title: 'Prince Of Darkness -',
          artist: 'SHADXWBXRN, Archez',
          censore: false,
          path: '../files/audio/playlist_3/4.mp3',
          duration: '2:04',
        },
        {
          id: 5,
          title: 'Wake Up -',
          artist: 'MoonDiety',
          censore: false,
          path: '../files/audio/playlist_3/5.mp3',
          duration: '2:18',
        },
        {
          id: 6,
          title: 'Killka -',
          artist: 'Ghostface Playa, fkbambam',
          censore: false,
          path: '../files/audio/playlist_3/6.mp3',
          duration: '2:22',
        },
        {
          id: 7,
          title: 'Call me ',
          artist: '(Slowed) - plenka',
          censore: false,
          path: '../files/audio/playlist_3/7.mp3',
          duration: '2:40',
        },
      ]
    },
    {
      id: 4,
      name: 'Лучшее русского рока',
      posterUrl: '../files/img/posters/rock.jpg',
      defaultLikes: 74320,
      defaultElect: true,
      tracks: [
        {
          id: 1,
          title: 'Что такое осень -',
          artist: 'ДДТ',
          censore: false,
          path: '../files/audio/playlist_4/1.mp3',
          duration: '4:57',
        },
        {
          id: 2,
          title: 'Как на войне -',
          artist: 'Агата Кристи',
          censore: false,
          path: '../files/audio/playlist_4/2.mp3',
          duration: '4:05',
        },
        {
          id: 3,
          title: 'На Заре -',
          artist: 'Альянс',
          censore: false,
          path: '../files/audio/playlist_4/3.mp3',
          duration: '5:46',
        },
        {
          id: 4,
          title: 'Дорога -',
          artist: 'Аукцыон',
          censore: false,
          path: '../files/audio/playlist_4/4.mp3',
          duration: '3:17',
        },
        {
          id: 5,
          title: 'Давай за... -',
          artist: 'ЛЮБЭ',
          censore: false,
          path: '../files/audio/playlist_4/5.mp3',
          duration: '4:10',
        },
        {
          id: 6,
          title: 'Прыгну со скалы -',
          artist: 'Король и Шут',
          censore: false,
          path: '../files/audio/playlist_4/6.mp3',
          duration: '3:13',
        },
        {
          id: 7,
          title: 'Полковнику никто не пишет -',
          artist: 'Би-2',
          censore: false,
          path: '../files/audio/playlist_4/7.mp3',
          duration: '4:56',
        },
        {
          id: 8,
          title: 'За окошком месяц май -',
          artist: 'Гарик Сукачёв',
          censore: false,
          path: '../files/audio/playlist_4/8.mp3',
          duration: '4:06',
        },
      ]
    },
  ]

export default playlists;